
name: Check code quality

on: [pull_request]

jobs:
  code-quality:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install black
        run: python -m pip install black
      - name: install isort
        run: python -m pip install isort 
      - name: install ruff
        run: python -m pip install ruff black
      - name: Run black
        run: python -m black --check .
      - name: Run isort
        run: python -m isort --check .
      - name: Run ruff
        run: python -m ruff .